### ISSUE TITLE
[ruby 3.4-dev] Digest::Blake3::metadata is not initialized properly

### ISSUE THREAD

**Issue by casperisfine** [Shopify/blake3-rb#11]
Since a couple days this gem fails on `ruby-head`:

```
TypeError: Digest::Blake3::metadata is not initialized properly
    test/blake3/digest_test.rb:92:in 'Class#new'
    test/blake3/digest_test.rb:92:in 'Blake3::DigestTest#test_clones_the_inner_state'
```

Likely because of https://github.com/ruby/digest/pull/59

**Comment by ianks** [comment]
This should be fixed in 1.5.4.2 once I click shipit
